# Generated by Django 5.0.6 on 2024-05-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_request', '0003_helprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
