# Generated by Django 5.0.6 on 2024-05-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_request', '0004_helprequest_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
