# Generated by Django 5.0.6 on 2024-08-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_request', '0005_helperprofile_latitude_helperprofile_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperprofile',
            name='sendbird_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
